version: '3.3'

services:
        frontend:
                build:
                        context: ./
                        dockerfile: ./frontend/Dockerfile
                command: ./run
                volumes:
                        - ./frontend:/frontend
                ports:
                        - 3001:3000
        backend:
                build:
                        context: ./
                        dockerfile: ./backend/Dockerfile                
                command: /start-reload.sh
                volumes:
                        - ./backend:/app
                ports:
                        - 80:80
