version: '3.3'

services:
        frontend:
                build:
                        context: ./
                        dockerfile: ./frontend/Dockerfile
                command: ./run
                volumes:
                        - ./frontend:/frontend
                ports:
                        - 3001:3000
                
